substitutions:
  device_name: kitchen_sink_light
  pretty_name: "Kitchen Sink Light"
  status_led: GPIO2
  restore_mode: ALWAYS_ON
  ip_address: 10.11.12.45

<<: !include ../devices/esp-01/relay-static.yaml
