substitutions:
  device_name: living_room_light_1
  pretty_name: "Living Room Light 1"
  status_led: GPIO2
  restore_mode: RESTORE_DEFAULT_ON
  ip_address: 10.2.1.51

<<: !include ../devices/esp-01/relay-static.yaml
