
esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m
  build_path: "./build/${device_name}"
  platformio_options:
      board_build.flash_mode: dout

<<: !include ../../common/wifi-static.yaml
<<: !include ../../common/captive_portal.yaml
<<: !include ../../common/api.yaml
<<: !include ../../common/ota.yaml

<<: !include ../../common/sensor/standard.yaml
<<: !include ../../common/text_sensor/standard.yaml

binary_sensor:
  - platform: status
    name: "${pretty_name} Status"

logger:
  baud_rate: 0
  level: VERBOSE

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:
