substitutions:
  device_name: freshwater_fill_valve
  pretty_name: "Freshwater Fill Valve"
  status_led: GPIO0
  restore_mode: RESTORE_DEFAULT_OFF
  ip_address: 10.11.12.63

<<: !include ../devices/esp-01/relay-static.yaml
